---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/orders":
    get:
      summary: list orders
      responses:
        '200':
          description: successful
    post:
      summary: create order
      responses:
        '200':
          description: successful
  "/api/v1/orders/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show order
      responses:
        '200':
          description: successful
  "/api/v1/products":
    get:
      summary: list products
      responses:
        '200':
          description: successful
    post:
      summary: create product
      responses:
        '200':
          description: successful
  "/api/v1/products/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show product
      responses:
        '200':
          description: successful
    patch:
      summary: update product
      responses:
        '200':
          description: successful
    put:
      summary: update product
      responses:
        '200':
          description: successful
    delete:
      summary: delete product
      responses:
        '200':
          description: successful
  "/api/v1/tokens":
    post:
      summary: create token
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
